In [11]:
# import sys

In [2]:
# sys.path.append('https://github.com/himoacs/iex_data/iex_data.py')

In [25]:
%matplotlib inline 
import matplotlib.pyplot as plt
from matplotlib import colors
import data_iex as IEX

In [26]:
dir(IEX)
# ?filter=symbol,volume,lastSalePrice

['API',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'io',
 'json',
 'json_normalize',
 'pd',
 'requests']

In [27]:
iex = IEX.API()
dir(iex)

['_GetDataFrame',
 '_IEX_URL_PREFIX',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'earnings',
 'financials',
 'latestNews',
 'latestTrade',
 'latestTradeQuote',
 'secUpper',
 'tradeBars']

In [28]:
iex.latestTrade(['AAPL', 'IBM', "FLR"])

In [29]:
iex.latestTradeQuote(['AAPL', 'IBM'])

,lastSaleTime,askSize,askPrice,lastSalePrice,bidPrice,bidSize,lastSaleSize,lastUpdated,volume
symbol,,,,,,,,,
AAPL,15:55:11.237000,100,186.73,186.76,186.69,100,100,15:58:04.469000,159628
IBM,15:57:46.760000,100,142.60,139.02,139.04,100,100,15:58:05.262000,44116

In [8]:
# %%timeit
iex.latestTrade(['AAPL', 'MSFT'])

In [20]:
# %%timeit -n 1
symList = ['AAPL', 'CSCO',"OXY","NFLX", "SBUX", "VXX", "MO", "PM", "TSLA","GE" ]
# symList = ['GE' ]
bars = iex.tradeBars(symList, bucket='1d')

# print (bars.columns)
bars

,symbol,date,minute,open,high,low,close,volume,marketOpen,marketHigh,marketLow,marketClose,marketVolume,average,marketAverage,label
0,AAPL,20180627,09:30,185.230,185.580,185.225,185.580,2072,185.240,185.660,185.180,185.660,521566,185.365,185.286,09:30 AM
1,AAPL,20180627,09:31,185.640,185.640,185.510,185.560,1910,185.640,185.750,185.228,185.710,99629,185.563,185.593,09:31 AM
2,AAPL,20180627,09:32,185.780,186.100,185.780,186.080,3850,185.732,186.160,185.690,185.909,156402,185.971,185.926,09:32 AM
3,AAPL,20180627,09:33,185.950,186.020,185.730,185.730,1407,185.910,186.030,185.250,185.635,93069,185.891,185.831,09:33 AM
4,AAPL,20180627,09:34,185.680,185.770,185.680,185.770,410,185.630,185.840,185.540,185.780,103142,185.721,185.713,09:34 AM
5,AAPL,20180627,09:35,185.810,185.920,185.810,185.920,1500,185.780,186.000,185.250,185.910,82782,185.837,185.847,09:35 AM
6,AAPL,20180627,09:36,185.950,186.110,185.950,186.020,2500,185.910,186.110,185.840,185.840,87608,186.046,185.985,09:36 AM
7,AAPL,20180627,09:37,185.975,186.050,185.955,186.040,562,185.840,186.050,185.820,186.042,57674,186.012,185.976,09:37 AM
8,AAPL,20180627,09:38,186.010,186.060,185.725,185.725,700,185.859,186.070,185.680,185.750,76496,185.849,185.893,09:38 AM
9,AAPL,20180627,09:39,185.865,185.865,185.830,185.830,200,185.730,185.998,185.730,185.830,60588,185.847,185.865,09:39 AM
10,AAPL,20180627,09:40,185.775,185.775,185.775,185.775,300,185.830,185.930,185.680,185.690,92064,185.775,185.812,09:40 AM
11,AAPL,20180627,09:41,185.730,185.800,185.700,185.770,600,185.700,185.818,185.570,185.700,82837,185.751,185.684,09:41 AM
12,AAPL,20180627,09:42,185.840,185.840,185.755,185.755,874,185.710,185.870,185.700,185.830,61857,185.820,185.788,09:42 AM
13,AAPL,20180627,09:43,185.825,186.010,185.825,186.000,547,185.825,186.020,185.770,185.955,98888,185.972,185.909,09:43 AM
14,AAPL,20180627,09:44,186.000,186.065,185.970,185.980,600,185.970,186.070,185.920,185.930,74280,186.006,186.005,09:44 AM
15,AAPL,20180627,09:45,185.995,185.995,185.960,185.960,300,185.950,186.020,185.250,185.954,57176,185.983,185.959,09:45 AM
16,AAPL,20180627,09:46,185.950,185.970,185.950,185.970,300,185.950,186.040,185.908,185.970,50017,185.960,185.968,09:46 AM
17,AAPL,20180627,09:47,185.860,185.980,185.860,185.980,540,185.960,186.000,185.820,185.967,69853,185.911,185.908,09:47 AM
18,AAPL,20180627,09:48,185.970,186.090,185.970,186.090,1757,185.980,186.100,185.960,186.090,71150,186.003,186.032,09:48 AM
19,AAPL,20180627,09:49,186.090,186.260,186.050,186.260,1996,186.095,186.260,186.030,186.110,143354,186.129,186.140,09:49 AM
20,AAPL,20180627,09:50,186.110,186.255,186.110,186.255,1500,186.120,186.260,186.100,186.260,71273,186.190,186.177,09:50 AM
21,AAPL,20180627,09:51,186.240,186.390,186.230,186.350,1720,186.250,186.400,186.200,186.354,94864,186.327,186.305,09:51 AM
22,AAPL,20180627,09:52,186.410,186.410,186.380,186.390,1300,186.360,186.430,186.320,186.330,71198,186.398,186.392,09:52 AM
23,AAPL,20180627,09:53,186.320,186.410,186.300,186.310,1224,186.325,186.410,186.230,186.300,93736,186.345,186.317,09:53 AM
24,AAPL,20180627,09:54,186.290,186.420,186.290,186.420,700,186.308,186.440,186.270,186.400,59933,186.332,186.336,09:54 AM
25,AAPL,20180627,09:55,186.380,186.380,186.310,186.330,359,186.400,186.420,186.250,186.300,84073,186.340,186.350,09:55 AM
26,AAPL,20180627,09:56,186.325,186.340,186.325,186.340,133,186.300,186.353,186.230,186.325,45771,186.329,186.309,09:56 AM
27,AAPL,20180627,09:57,186.335,186.335,186.280,186.300,900,186.320,186.340,186.230,186.272,34634,186.302,186.287,09:57 AM
28,AAPL,20180627,09:58,186.315,186.335,186.265,186.265,596,186.260,186.350,186.250,186.292,42330,186.293,186.299,09:58 AM
29,AAPL,20180627,09:59,186.230,186.340,186.230,186.340,930,186.280,186.360,186.230,186.360,39150,186.306,186.292,09:59 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,GE,20180627,11:07,14.245,14.260,14.240,14.255,24045,14.240,14.260,14.234,14.254,261442,14.249,14.250,11:07 AM
98,GE,20180627,11:08,14.255,14.255,14.255,14.255,9401,14.257,14.260,14.250,14.255,136599,14.255,14.253,11:08 AM
99,GE,20180627,11:09,14.255,14.260,14.255,14.255,8850,14.260,14.260,14.236,14.260,119702,14.255,14.255,11:09 AM
100,GE,20180627,11:10,14.255,14.260,14.255,14.255,20962,14.260,14.260,14.248,14.260,154406,14.256,14.256,11:10 AM
101,GE,20180627,11:11,14.255,14.290,14.255,14.290,18582,14.260,14.290,14.250,14.285,281343,14.273,14.266,11:11 AM
102,GE,20180627,11:12,14.285,14.285,14.270,14.280,59609,14.290,14.290,14.266,14.280,360465,14.282,14.280,11:12 AM
103,GE,20180627,11:13,14.285,14.290,14.285,14.290,1315,14.280,14.290,14.280,14.280,78280,14.287,14.285,11:13 AM
104,GE,20180627,11:14,14.285,14.285,14.275,14.275,5300,14.289,14.290,14.270,14.275,103961,14.279,14.279,11:14 AM
105,GE,20180627,11:15,14.280,14.290,14.280,14.285,8285,14.277,14.290,14.270,14.280,147465,14.282,14.283,11:15 AM
106,GE,20180627,11:16,14.285,14.285,14.270,14.270,4500,14.285,14.290,14.270,14.271,188502,14.282,14.279,11:16 AM
107,GE,20180627,11:17,14.275,14.275,14.275,14.275,300,14.275,14.281,14.270,14.275,40451,14.275,14.275,11:17 AM
108,GE,20180627,11:18,14.275,14.275,14.250,14.255,23783,14.280,14.280,14.250,14.259,301236,14.269,14.268,11:18 AM
109,GE,20180627,11:19,14.255,14.265,14.250,14.265,8100,14.255,14.272,14.250,14.265,215747,14.260,14.260,11:19 AM
110,GE,20180627,11:20,14.265,14.280,14.265,14.275,10075,14.260,14.280,14.260,14.278,165912,14.271,14.271,11:20 AM
111,GE,20180627,11:21,14.275,14.285,14.265,14.280,7533,14.275,14.285,14.260,14.280,249734,14.271,14.272,11:21 AM
112,GE,20180627,11:22,14.285,14.290,14.285,14.285,1105,NaN,-1.000,-1.000,NaN,0,14.287,-1.000,11:22 AM
113,GE,20180627,11:23,14.285,14.285,14.275,14.275,2500,NaN,-1.000,-1.000,NaN,0,14.279,-1.000,11:23 AM
114,GE,20180627,11:24,14.270,14.270,14.260,14.260,3888,NaN,-1.000,-1.000,NaN,0,14.267,-1.000,11:24 AM
115,GE,20180627,11:25,14.255,14.265,14.255,14.265,2500,NaN,-1.000,-1.000,NaN,0,14.259,-1.000,11:25 AM
116,GE,20180627,11:26,14.265,14.265,14.245,14.250,1708,NaN,-1.000,-1.000,NaN,0,14.251,-1.000,11:26 AM
117,GE,20180627,11:27,14.245,14.245,14.240,14.245,35796,NaN,-1.000,-1.000,NaN,0,14.245,-1.000,11:27 AM
118,GE,20180627,11:28,14.245,14.245,14.235,14.235,37600,NaN,-1.000,-1.000,NaN,0,14.243,-1.000,11:28 AM
119,GE,20180627,11:29,14.235,14.245,14.230,14.245,278530,NaN,-1.000,-1.000,NaN,0,14.244,-1.000,11:29 AM
120,GE,20180627,11:30,14.245,14.245,14.235,14.235,21988,NaN,-1.000,-1.000,NaN,0,14.244,-1.000,11:30 AM
121,GE,20180627,11:31,14.240,14.240,14.235,14.235,1535,NaN,-1.000,-1.000,NaN,0,14.236,-1.000,11:31 AM
122,GE,20180627,11:32,14.235,14.265,14.235,14.265,33706,NaN,-1.000,-1.000,NaN,0,14.245,-1.000,11:32 AM
123,GE,20180627,11:33,14.260,14.260,14.255,14.260,2900,NaN,-1.000,-1.000,NaN,0,14.256,-1.000,11:33 AM
124,GE,20180627,11:34,14.255,14.260,14.250,14.255,3000,NaN,-1.000,-1.000,NaN,0,14.255,-1.000,11:34 AM
125,GE,20180627,11:35,14.260,14.280,14.260,14.280,2400,NaN,-1.000,-1.000,NaN,0,14.263,-1.000,11:35 AM
126,GE,20180627,11:36,14.280,14.280,14.275,14.275,14470,NaN,-1.000,-1.000,NaN,0,14.280,-1.000,11:36 AM

In [21]:
# bars[[ 'symbol','date', 'minute','open','high', 'low', 'close','volume','marketOpen',
#           'marketHigh','marketLow', 'marketClose', 'marketVolume', 'average','marketAverage',  
#        'numberOfTrades', 'marketNumberOfTrades', 
#          ]]

In [22]:
# bar =
try:     bar = bars[['symbol','date','minute','open','high', 'low', 'close',  'volume',]]
except:  bar = bars[['symbol','date','open','high', 'low', 'close',  'volume',]]

In [23]:
bar[bar['symbol']=="GE"]

    symbol      date minute    open    high     low   close  volume
0       GE  20180627  09:30  13.845  13.910  13.810  13.910    3500
1       GE  20180627  09:31  13.910  13.910  13.880  13.885   14084
2       GE  20180627  09:32  13.855  13.855  13.835  13.840   21100
3       GE  20180627  09:33  13.855  13.915  13.855  13.885   46820
4       GE  20180627  09:34  13.885  13.925  13.865  13.905   70836
5       GE  20180627  09:35  13.905  13.930  13.905  13.925   12224
6       GE  20180627  09:36  13.925  13.955  13.920  13.925    9732
7       GE  20180627  09:37  13.930  13.960  13.915  13.915   37537
8       GE  20180627  09:38  13.910  13.940  13.895  13.910    9638
9       GE  20180627  09:39  13.900  13.940  13.890  13.940   12085
10      GE  20180627  09:40  13.935  14.025  13.935  14.025   23921
11      GE  20180627  09:41  14.025  14.030  14.000  14.000   24759
12      GE  20180627  09:42  14.000  14.020  13.985  14.005   22479
13      GE  20180627  09:43  14.005  14.075  14.000  14.075   25651
14      GE  20180627  09:44  14.080  14.090  14.065  14.080   29084
15      GE  20180627  09:45  14.080  14.100  14.030  14.100   71389
16      GE  20180627  09:46  14.100  14.200  14.090  14.160   48093
17      GE  20180627  09:47  14.160  14.225  14.120  14.210   46741
18      GE  20180627  09:48  14.210  14.210  14.190  14.210   23333
19      GE  20180627  09:49  14.210  14.240  14.180  14.180   22871
20      GE  20180627  09:50  14.190  14.240  14.160  14.240   10659
21      GE  20180627  09:51  14.250  14.335  14.245  14.290   26951
22      GE  20180627  09:52  14.260  14.260  14.210  14.220    7760
23      GE  20180627  09:53  14.215  14.240  14.215  14.230    3560
24      GE  20180627  09:54  14.190  14.225  14.185  14.205    6750
25      GE  20180627  09:55  14.200  14.205  14.145  14.180    9300
26      GE  20180627  09:56  14.185  14.220  14.185  14.220    6015
27      GE  20180627  09:57  14.220  14.225  14.210  14.225   10373
28      GE  20180627  09:58  14.225  14.250  14.215  14.240   16972
29      GE  20180627  09:59  14.245  14.260  14.230  14.240    5695
..     ...       ...    ...     ...     ...     ...     ...     ...
97      GE  20180627  11:07  14.245  14.260  14.240  14.255   24045
98      GE  20180627  11:08  14.255  14.255  14.255  14.255    9401
99      GE  20180627  11:09  14.255  14.260  14.255  14.255    8850
100     GE  20180627  11:10  14.255  14.260  14.255  14.255   20962
101     GE  20180627  11:11  14.255  14.290  14.255  14.290   18582
102     GE  20180627  11:12  14.285  14.285  14.270  14.280   59609
103     GE  20180627  11:13  14.285  14.290  14.285  14.290    1315
104     GE  20180627  11:14  14.285  14.285  14.275  14.275    5300
105     GE  20180627  11:15  14.280  14.290  14.280  14.285    8285
106     GE  20180627  11:16  14.285  14.285  14.270  14.270    4500
107     GE  20180627  11:17  14.275  14.275  14.275  14.275     300
108     GE  20180627  11:18  14.275  14.275  14.250  14.255   23783
109     GE  20180627  11:19  14.255  14.265  14.250  14.265    8100
110     GE  20180627  11:20  14.265  14.280  14.265  14.275   10075
111     GE  20180627  11:21  14.275  14.285  14.265  14.280    7533
112     GE  20180627  11:22  14.285  14.290  14.285  14.285    1105
113     GE  20180627  11:23  14.285  14.285  14.275  14.275    2500
114     GE  20180627  11:24  14.270  14.270  14.260  14.260    3888
115     GE  20180627  11:25  14.255  14.265  14.255  14.265    2500
116     GE  20180627  11:26  14.265  14.265  14.245  14.250    1708
117     GE  20180627  11:27  14.245  14.245  14.240  14.245   35796
118     GE  20180627  11:28  14.245  14.245  14.235  14.235   37600
119     GE  20180627  11:29  14.235  14.245  14.230  14.245  278530
120     GE  20180627  11:30  14.245  14.245  14.235  14.235   21988
121     GE  20180627  11:31  14.240  14.240  14.235  14.235    1535
122     GE  20180627  11:32  14.235  14.265  14.235  14.265   33706
123     GE  20180627  11:33  14.260  14.260  14.255  14.260    2900
124     GE  20180627  11:34  14.255  14.260  14.250  14.255    3000
125     GE  20180627  11:35  14.260  14.280  14.260  14.280    2400
126     GE  20180627  11:36  14.280  14.280  14.275  14.275   14470

[127 rows x 8 columns]

In [15]:
https://api.iextrading.com/1.0/tops/last/?symbols=SNAP,fb,AIG%2b&format=csv

SyntaxError: invalid syntax (<ipython-input-15-366dc211e16f>, line 1)

In [33]:
# https://api.iextrading.com/1.0/tops/?symbols=SNAP,fb,AIG%2b&format=csv

SyntaxError: invalid syntax (<ipython-input-33-2328fbbe4804>, line 1)

In [21]:
import pandas as pd
from urllib.request import Request, urlopen
import json
from pandas.io.json import json_normalize
import requests, io

In [22]:
_IEX_URL_PREFIX = r'https://api.iextrading.com/1.0/'

In [54]:
def get_trade_bars_data2( securities, bucket='1m'):

        """
        Get bucketed trade/volume data. Supported buckets are: 1m, 3m, 6m, 1y, ytd, 2y, 5y
        :param securities: list of securities
        :param bucket:
        :return: dataframe
        """
        # securities = self.return_valid_securities(securities)
        #https://api.iextrading.com/1.0/stock/market/batch?&types=time-series&range=5y&symbols=qep,oxy,flr,mo,pm,nflx
        
        syms     = (',').join(securities)
        df       = pd.DataFrame()
        # Get price data for each security and then append the results together
        # if securities:

        #     for symbol in securities:
        #         suffix          = r'stock/{symbol}/chart/{bucket}'.format(symbol=symbol,bucket=bucket)
        #         df              = self._url_to_dataframe(self._IEX_URL_PREFIX + suffix)
        #         df['symbol']    = symbol
        #         final_df        = final_df.append(df, ignore_index=True)
        #     return final_df
        # else:   print('These stock(s) are invalid!')

        # if securities:    
            # for symbol in securities:
            
        suffix  = r"stock/market/batch?&types=time-series&range={bucket}&symbols={symbol}".format(bucket=bucket,symbol=syms)
        filter  = "&filter=symbol,date,open,high,low,close,volume,changePercent,vwap"
        urlData = requests.get(_IEX_URL_PREFIX + suffix+filter).content
        rawData = json.loads(urlData)
        
        for sym in list(rawData.keys()):    
            _df           =  pd.DataFrame(list(rawData.get(sym).values())[0])
            _df["symbol"] = sym
            print (_df.head())
            df = pd.concat([df,_df])
           
        
        return df

In [53]:
# %%timeit -n 1
securities = ['AAPL', 'CSCO',"OXY","NFLX", "SBUX", "VXX", "MO", "PM" ]
bars = get_trade_bars_data2( securities, bucket='2y')

   changePercent    close        date     high      low     open    volume  \
0          1.271  93.1697  2016-05-23  93.9040  92.4354  92.6286  38018643
1          1.524  94.5900  2016-05-24  94.7735  93.5658  93.9329  35140174
2          1.757  96.2518  2016-05-25  96.3677  94.7929  95.3339  38642108
3          0.793  97.0151  2016-05-26  97.3243  95.3049  96.3098  56331159
4         -0.060  96.9571  2016-05-27  97.0731  95.8895  96.0779  36341240

      vwap symbol
0  93.3771   AAPL
1  94.2808   AAPL
2  95.7591   AAPL
3  96.3515   AAPL
4  96.5612   AAPL
   changePercent    close        date     high      low     open    volume  \
0         -0.107  26.1068  2016-05-23  26.3964  25.9573  25.9573  19850040
1          1.897  26.6020  2016-05-24  26.7048  26.1722  26.1722  26514828
2          1.581  27.0225  2016-05-25  27.0972  26.6487  26.7048  25729908
3         -0.069  27.0038  2016-05-26  27.1346  26.9057  26.9664  19366299
4          0.069  27.0225  2016-05-27  27.1299  26.9010  27.0505  16673324

      vwap symbol
0  26.2496   CSCO
1  26.5854   CSCO
2  26.9954   CSCO
3  27.0286   CSCO
4  27.0029   CSCO
   changePercent    close        date     high      low     open   volume  \
0         -0.120  68.3968  2016-05-23  68.8536  67.8852  68.0405  3334451
1          1.670  69.5388  2016-05-24  69.7854  68.4973  69.0089  3620728
2          0.066  69.5844  2016-05-25  70.6624  69.3195  70.2239  3399508
3         -0.079  69.5296  2016-05-26  70.5071  69.4748  70.0686  2286839
4          0.053  69.5662  2016-05-27  69.6301  69.0454  69.4017  2203127

      vwap symbol
0  68.4580    OXY
1  69.4648    OXY
2  69.7519    OXY
3  69.8131    OXY
4  69.3975    OXY
   changePercent   close        date      high     low    open    volume  \
0          2.595   94.89  2016-05-23   95.2924   92.85   92.98  13992330
1          3.162   97.89  2016-05-24   99.1400   95.75   95.98  21246023
2          2.360  100.20  2016-05-25  100.3100   98.30   99.00  15211295
3          2.605  102.81  2016-05-26  104.0000  101.38  103.21  17824673
4          0.477  103.30  2016-05-27  103.5000  101.44  102.44   9092127

       vwap symbol
0   94.5605   NFLX
1   97.8675   NFLX
2   99.2864   NFLX
3  102.7704   NFLX
4  102.5826   NFLX
   changePercent    close        date     high      low     open   volume  \
0         -0.037  52.6105  2016-05-23  52.8197  52.3128  52.6298  7352054
1          1.538  53.4199  2016-05-24  53.5934  52.6876  52.7454  7748697
2         -0.523  53.1405  2016-05-25  53.4392  52.9478  53.1887  8126058
3          0.254  53.2754  2016-05-26  53.8342  52.9478  53.5259  9451708
4         -0.253  53.1405  2016-05-27  53.5259  53.0923  53.3428  6631120

      vwap symbol
0  52.6105   SBUX
1  53.2790   SBUX
2  53.2011   SBUX
3  53.2509   SBUX
4  53.2845   SBUX
   changePercent   close        date      high     low    open   volume  \
0         -0.464  240.48  2016-05-23  243.3184  237.12  241.12  2825376
1         -4.325  230.08  2016-05-24  237.1200  227.44  236.80  3872151
2         -1.878  225.76  2016-05-25  228.6400  221.36  226.48  3422037
3         -1.063  223.36  2016-05-26  226.2400  222.40  225.44  2740833
4         -2.686  217.36  2016-05-27  222.5600  217.12  221.60  2757274

       vwap symbol
0  239.5273    VXX
1  232.1445    VXX
2  224.9995    VXX
3  224.1171    VXX
4  219.6263    VXX
   changePercent    close        date     high      low     open   volume  \
0          0.445  58.7608  2016-05-23  58.8630  58.3613  58.5285  3709788
1          0.870  59.2719  2016-05-24  59.5803  59.0117  59.0860  5209705
2          0.204  59.3927  2016-05-25  59.6064  59.1325  59.2719  4265913
3          0.125  59.4670  2016-05-26  59.5506  59.1432  59.3276  3732653
4         -0.063  59.4298  2016-05-27  59.7179  59.1604  59.5227  3255749

      vwap symbol
0  58.6949     MO
1  59.3222     MO
2  59.4220     MO
3  59.3803     MO
4  59.3966     MO
   changePercent    close        date     high      low     open   volume  \
0          0.245  90.7501  2016-05-23  90.8794  90.2423  90.5470  2365439
1          0.570  91.2672  2016-05-24  91.7566  91.0364  91.1472  3074422
2          0.212  91.4611  2016-05-25  91.8767  91.0918  91.1103  2543136
3         -0.040  91.4242  2016-05-26  91.5673  90.9164  91.4611  2350547
4          0.172  91.5812  2016-05-27  91.7382  91.1472  91.5073  2059805

      vwap symbol
0  90.6034     PM
1  91.3768     PM
2  91.5345     PM
3  91.3463     PM
4  91.5329     PM

In [47]:
# list(rd.keys())[0]
# _df = pd.DataFrame()

In [48]:
# _df = pd.DataFrame()
# print (_df.head())


# # for sym in list(rd.keys()):    
#     df           =  pd.DataFrame(list(rd.get(sym).values())[0])
#     df["symbol"] = sym
#     _df = pd.concat([_df,df])
# print (_df.head())

In [34]:
bar[bar['symbol']=="OXY"]

    symbol      date    open    high     low   close  volume
0      OXY  20180626  81.850  81.860  81.850  81.860     127
1      OXY  20180626     NaN  -1.000  -1.000     NaN       0
2      OXY  20180626  81.985  81.985  81.985  81.985     100
3      OXY  20180626     NaN  -1.000  -1.000     NaN       0
4      OXY  20180626  81.940  82.190  81.940  82.190    2000
5      OXY  20180626  82.105  82.175  82.090  82.175     400
6      OXY  20180626  82.050  82.050  82.050  82.050     100
7      OXY  20180626  82.055  82.070  81.900  81.900     400
8      OXY  20180626  81.855  81.970  81.855  81.970     212
9      OXY  20180626  81.920  81.920  81.920  81.920     200
10     OXY  20180626     NaN  -1.000  -1.000     NaN       0
11     OXY  20180626     NaN  -1.000  -1.000     NaN       0
12     OXY  20180626  81.950  81.950  81.950  81.950     100
13     OXY  20180626     NaN  -1.000  -1.000     NaN       0
14     OXY  20180626  81.795  81.820  81.795  81.820     700
15     OXY  20180626  81.640  81.640  81.640  81.640     100
16     OXY  20180626     NaN  -1.000  -1.000     NaN       0
17     OXY  20180626  81.540  81.540  81.510  81.510     400
18     OXY  20180626     NaN  -1.000  -1.000     NaN       0
19     OXY  20180626  81.725  81.760  81.725  81.760     200
20     OXY  20180626  81.870  81.870  81.870  81.870     200
21     OXY  20180626  81.770  81.770  81.770  81.770     100
22     OXY  20180626  81.750  81.750  81.750  81.750     100
23     OXY  20180626  81.645  81.730  81.645  81.725     900
24     OXY  20180626  81.660  81.660  81.660  81.660     100
25     OXY  20180626     NaN  -1.000  -1.000     NaN       0
26     OXY  20180626  81.515  81.535  81.515  81.535     300
27     OXY  20180626  81.520  81.530  81.490  81.490     339
28     OXY  20180626  81.495  81.530  81.495  81.530     200
29     OXY  20180626     NaN  -1.000  -1.000     NaN       0
..     ...       ...     ...     ...     ...     ...     ...
341    OXY  20180626  82.730  82.770  82.730  82.770     500
342    OXY  20180626  82.745  82.795  82.740  82.795     600
343    OXY  20180626  82.795  82.810  82.795  82.810     300
344    OXY  20180626     NaN  -1.000  -1.000     NaN       0
345    OXY  20180626  82.840  82.890  82.840  82.890     800
346    OXY  20180626  82.860  82.860  82.840  82.840     600
347    OXY  20180626  82.790  82.790  82.790  82.790     300
348    OXY  20180626  82.800  82.800  82.800  82.800     100
349    OXY  20180626     NaN  -1.000  -1.000     NaN       0
350    OXY  20180626  82.745  82.805  82.745  82.800     600
351    OXY  20180626  82.770  82.770  82.770  82.770      50
352    OXY  20180626  82.670  82.690  82.670  82.690     400
353    OXY  20180626  82.685  82.695  82.645  82.645     800
354    OXY  20180626     NaN  -1.000  -1.000     NaN       0
355    OXY  20180626  82.650  82.650  82.600  82.600     457
356    OXY  20180626  82.590  82.630  82.590  82.630    2400
357    OXY  20180626  82.630  82.630  82.630  82.630     700
358    OXY  20180626  82.535  82.570  82.535  82.570     200
359    OXY  20180626  82.520  82.550  82.520  82.540    1000
360    OXY  20180626  82.570  82.570  82.540  82.540     200
361    OXY  20180626  82.540  82.570  82.515  82.570     700
362    OXY  20180626  82.600  82.620  82.585  82.600     620
363    OXY  20180626  82.610  82.610  82.590  82.590    1200
364    OXY  20180626  82.590  82.630  82.590  82.630    1320
365    OXY  20180626  82.630  82.650  82.630  82.650     994
366    OXY  20180626  82.670  82.670  82.600  82.620     850
367    OXY  20180626  82.610  82.610  82.585  82.590    1800
368    OXY  20180626  82.585  82.640  82.585  82.640    3300
369    OXY  20180626  82.645  82.670  82.640  82.650    2132
370    OXY  20180626  82.650  82.690  82.605  82.680    4568

[371 rows x 7 columns]

In [67]:
final_df

Empty DataFrame
Columns: []
Index: []

In [50]:
securities = ['oxy', "QEP","VXX","HI"]

In [92]:
str(securities).replace('"', "").replace("'", "").replace('[', "").replace(']', "").replace(' ', "")

'oxy,QEP,VXX,HI'

In [51]:
(',').join(securities)

'oxy,QEP,VXX,HI'

In [38]:
dllist = list(range(821))
print (round((len(dllist)),-2)/100+1)

9.0

In [43]:
dll    = [ dllist[ x*100: (x+1)*100]  for x in  range(int(round((len(dllist)),-2)/100+1))  ]

In [42]:
range(int(round((len(dllist)),-2)/100+1))

range(0, 9)

In [44]:
dll

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
 [100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199],
 [200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299],
 [300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399],
 [400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499],
 [500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599],
 [600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699],
 [700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799],
 [800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  820]]